[package]
name = "bindings_generator"
edition = "2021"
version = "0.0.1"
publish = false

[dependencies]
bindgen = { version = "0.70.1", git = "https://github.com/rust-lang/rust-bindgen" }
cmake = "0.1"
cruet = "0.14.0"