[package]
name = "spirv-cross2-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0" }
quote = "1.0"
proc-macro2 = "1.0.86"

[dev-dependencies]
spirv-cross-sys = { version = "0.1.0", path = "../spirv-cross-sys"}